@startuml Принципиальная схема

() "Рабочий источник" as РИст #Green
() "Тестовый источник" as ТИст #Darkorange
() "Временный источник" as ВИст #Blue

РИст ..> ТИст : Потомок
ТИст ..> ВИст : Потомок

component "ЕСД"{
    port "Коннектор Вх" as ЕВх

    component "Маршрутизатор контуров"{
        port "Вход" as МВх
        portout "Рабочий" as МРаб
        portout "Тестовый" as МТест
        portout "Временный" as МВрем

        МВх --> МРаб #Green
        МВх ..> МТест #Green
        МВх ..> МВрем #Green

        МВх --> МТест #Darkorange
        МВх ..> МВрем #Darkorange

        МВх --> МВрем #Blue
    }
    component "Проверка пакета"{
        port "Данные\nРабочий" as ПДРаб
        port "Схема\nРабочий" as ПСРаб
        port "Данные\nТестовый" as ПДТест
        port "Схема\nТестовый" as ПСТест
        port "Данные\nВременный" as ПДВрем
        port "Схема\nВременный" as ПСВрем
        portout "Пройдено Рабочий" as ПРРаб
        portout "Пройдено Тестовый" as ПРТест
        portout "Пройдено Временный" as ПРВрем

        component "Проверка Рабочий" as ПР
        component "Проверка Тестовый" as ПТ
        component "Проверка Временный" as ПВ

        ПДРаб --> ПР
        ПСРаб --> ПР
        ПР --> ПРРаб

        ПДТест --> ПТ
        ПСТест --> ПТ
        ПТ --> ПРТест

        ПДВрем --> ПВ
        ПСВрем --> ПВ
        ПВ --> ПРВрем
    }
    component "Управление моделью данных"{
        portout "Работа с моделью Git" as УМД
        portout "Настройка структуры БД" as УМБ
        portout "Схемы данных" as УМС
    }

    УМС --> ПСРаб
    УМС --> ПСТест
    УМС --> ПСВрем

    component "Управление корпоративным хранилищем" as УКХ
    component "Маршрутизация" as УМ
    component "Конвертация" as УК

    ПРРаб --> УКХ
    ПРТест --> УКХ
    ПРВрем --> УКХ

    УКХ --> УМ

    УМ --> УК
}
component " "{
    portout "Коннектор\nGit (чтение)" as ЕИсхГитЧтение
    portout "Коннектор\nGit (запись)" as ЕИсхГитЗапись
    portout "Коннектор\nБД (объекты)" as ЕИсхБДОб
    portout "Коннектор\nБД (графы)" as ЕИсхБДГр

    portout "Коннектор\nИсх" as ЕИсх

}
    УК --> ЕИсх

    УКХ --> ЕИсхБДОб
    УКХ --> ЕИсхБДГр

() "Git (master)" as ГРаб #Green
() "Git (prerelease)" as ГТест #Darkorange
() "Git (issue)" as ГВрем #Blue

() "Графовая БД" as ГБД
() "Объектная БД" as ОБД
() "Объектно-графовая БД" as ОГБД

ГРаб ..> ГТест : Потомок
ГТест ..> ГВрем : Потомок

УМД --> ЕИсхГитЧтение
УМД --> ЕИсхГитЗапись

ЕИсхГитЧтение --> ГРаб #Green
ЕИсхГитЧтение --> ГТест #Darkorange
ЕИсхГитЧтение --> ГВрем #Blue
ЕИсхГитЗапись --> ГВрем #Blue

УМБ --> ЕИсхБДОб
УМБ --> ЕИсхБДГр

ЕИсхБДГр --> ГБД
ЕИсхБДГр --> ОГБД
ЕИсхБДОб --> ОБД
ЕИсхБДОб --> ОГБД

РИст --> ЕВх #Green
ТИст --> ЕВх #Darkorange
ВИст --> ЕВх #Blue

ЕВх --> МВх #Green
ЕВх --> МВх #Darkorange
ЕВх --> МВх #Blue

МРаб --> ПДРаб
МТест --> ПДТест
МВрем --> ПДВрем

() "Приемник"
ЕИсх --> Приемник

@enduml