name: Контроль качества
on:
  push:
    branches:
      - main
      - develop
      - release*
  pull_request:
    types: [opened, synchronize, reopened]
    
env:
  # отключение безопасности установки
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  SonarScanner:
    if: github.repository == 'aagorlan/onec-esb-kb'
    runs-on: ubuntu-latest

    steps:
      # Загрузка проекта
      - name: Актуализация
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      - name: Извлечение имени текущей ветки
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Установка Sonar-scanner
        uses: warchant/setup-sonar-scanner@v1

      # Анализ проекта в SonarQube (ветка)
      - name: Анализ в SonarQube (branch)
        if: github.event_name == 'push'
        run: sonar-scanner
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }}

      # Анализ проекта в SonarQube (PR)
      # https://docs.sonarqube.org/latest/analysis/pull-request/
      - name: Анализ в SonarQube (pull-request)
        if: github.event_name == 'pull_request'
        run: sonar-scanner
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
